### ISSUE TITLE
Version upgrade required.

### ISSUE THREAD

**Issue by shiv19** [rcluan/nativescript-material-showcaseview#1]
https://github.com/rcluan/nativescript-material-showcaseview/blob/18981c528be27fa21bddfd7fef8a58dfae4b786d/platforms/android/include.gradle#L19

Latest version is 1.2.0

1.1.0 no longer exists on that github repo

**Comment by rcluan** [comment]
Hi @shiv19 

Thanks for pointing this out, but "1.1.0" is the default version used when `project.materialShowcaseViewVersion` is not defined. Do you think it is necessary to update the default version or setting the `project.materialShowcaseViewVersion` is enough?

Cheers.

**Comment by shiv19** [comment]
updating `project.materialShowcaseViewVersion` should be enough. But in the next patch version of this plugin (maybe when adding {N} 6 support, it would be nice to update the fallback version as well :))
